using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices;
using System.Runtime.Remoting.Messaging;
using System.IO;
using System.Text;
using Newtonsoft.Json;
using System.Threading.Tasks;
using System.Security.Cryptography;

namespace gestione_account_password
{
    /// <summary>
    /// 
    /// </summary>
    public class PasswordManager
    {
        private static readonly char[] _lowercaseLetters =
        {
            'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'
        };

        private static readonly char[] _uppercaseLetters =
        {
            'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z'
        };

        private static readonly char[] _numbers =
        {
            '0', '1', '2', '3', '4', '5', '6', '7', '8', '9'
        };

        private static readonly char[] _specialChars =
        {
            '!', '@', '#', '$', '%', '^', '&', '*', '(', ')', '-', '_', '+', '=', '{', '}', '[', ']', '|', '\\', ':', ';', '"', '\'', '<', '>', ',', '.', '?', '/'
        };

        private string _password;

        public static char[] LowercaseLetters
        {
            get => _lowercaseLetters;
        }

        public static char[] UppercaseLetters
        {
            get => _uppercaseLetters;
        }

        public static char[] Numbers
        {
            get => _numbers;
        }

        public static char[] SpecialChars
        {
            get => _specialChars;
        }

        public string Password
        {
            get => _password;
            set => _password = value;
        }

        /// <summary>
        /// Base constructor for a password
        /// </summary>
        public PasswordManager()
        {
            Password = "default";
        }

        /// <summary>
        /// Constructor for a password generated by me
        /// </summary>
        /// <param name="length"> Length of the password </param>
        /// <param name="caps"> True: upper case letters are allowed in the password, false: upper case letters aren't allowed in the password </param>
        /// <param name="numbers"> True: numbers are allowed in the password, false: numbers aren't allowed in the password </param>
        /// <param name="specialChars"> True: special characters are allowed in the password, false: special characters aren't allowed in the password </param>
        /// <param name="username"> Used as a unique key for encryption </param>
        public PasswordManager(int length, bool caps, bool numbers, bool specialChars, string username)
        {
            Password = PasswordGenerator(length, caps, numbers, specialChars, username);
        }

        /// <summary>
        /// Constructor for a password that needs to be encrypted
        /// </summary>
        /// <param name="password"> Plain password </param>
        /// <param name="username"> Used as a unique key for encryption </param>
        public PasswordManager(string password, string username)
        {
            Password = EncryptPassword(password, username);
        }

        /// <summary>
        /// Constructor for a password
        /// </summary>
        /// <param name="encryptedPassword"> Password already encrypted and ready to be stored </param>
        public PasswordManager(string encryptedPassword)
        {
            Password = encryptedPassword;
        }

        /// <summary>
        /// Generates a random password
        /// </summary>
        /// <param name="length"> Length of the password </param>
        /// <param name="caps"> True: upper case letters are allowed in the password, false: upper case letters aren't allowed in the password </param>
        /// <param name="numbers"> True: numbers are allowed in the password, false: numbers aren't allowed in the password </param>
        /// <param name="specialChars"> True: special characters are allowed in the password, false: special characters aren't allowed in the password </param>
        /// <param name="username"> Used as a unique key for encryption </param>
        /// <returns> Encrypted password </returns>
        /// <exception cref="ArgumentOutOfRangeException"> Length of the password must be between 8 and 30 chars for security reasons </exception>
        public string PasswordGenerator(int length, bool caps, bool numbers, bool specialChars, string username)
        {
            if (length < 8 || length > 32)
            {
                throw new ArgumentOutOfRangeException();
            }

            Random rng = new();
            StringBuilder pw = new();
            char[] allowedChars = LowercaseLetters;

            if (caps)
                allowedChars = ConcatArrays(allowedChars, UppercaseLetters);
            if (numbers)
                allowedChars = ConcatArrays(allowedChars, Numbers);
            if (specialChars)
                allowedChars = ConcatArrays(allowedChars, SpecialChars);

            for (int i = 0; i < length; i++)
            {
                pw.Append(allowedChars[rng.Next(allowedChars.Length)]);
            }

            string encryptedPassword = EncryptPassword(pw.ToString(), username);
            return encryptedPassword;
        }

        /// <summary>
        /// Method to determine the array of allowed characters for the password
        /// </summary>
        /// <param name="arrays"> Small arrays that contain all characters of a category </param>
        /// <returns> Array of allowed characters </returns>
        private static char[] ConcatArrays(params char[][] arrays)
        {
            int totalLength = 0;
            foreach (char[] array in arrays)
            {
                totalLength += array.Length;
            }

            char[] result = new char[totalLength];
            int offset = 0;
            foreach (char[] array in arrays)
            {
                Array.Copy(array, 0, result, offset, array.Length);
                offset += array.Length;
            }

            return result;
        }

        /// <summary>
        /// Method to get the key for encryption and decryption
        /// </summary>
        /// <param name="username"> Used as a unique string to get the key </param>
        /// <returns> Key used for encryption and decryption as an array of bytes </returns>
        private byte[] GetKey(string username)
        {
            byte[] key = Encoding.UTF8.GetBytes(username);

            while (key.Length < 32)
            {
                key = key.Concat(Encoding.UTF8.GetBytes(username)).ToArray();
            }

            if (key.Length > 32)
            {
                key = key.Take(32).ToArray();
            }

            return key;
        }

        /// <summary>
        /// Encrypts the password
        /// </summary>
        /// <param name="password"> Plain password </param>
        /// <param name="username"> Used to get the key for encrypting the password </param>
        /// <returns> Encrypted password and IV to decrypt separated from a dash </returns>
        public string EncryptPassword(string password, string username)
        {
            byte[] key = GetKey(username);

            using (Aes aesAlg = Aes.Create())
            {
                aesAlg.Key = key;
                aesAlg.GenerateIV();

                byte[] iv = aesAlg.IV;

                using (ICryptoTransform encryptor = aesAlg.CreateEncryptor(aesAlg.Key, aesAlg.IV))
                {
                    using (MemoryStream msEncrypt = new MemoryStream())
                    {
                        using (CryptoStream csEncrypt = new CryptoStream(msEncrypt, encryptor, CryptoStreamMode.Write))
                        {
                            using (StreamWriter swEncrypt = new StreamWriter(csEncrypt))
                            {
                                swEncrypt.Write(password);
                            }
                        }

                        byte[] encrypted = msEncrypt.ToArray();
                        string encryptedPassword = Convert.ToBase64String(encrypted);
                        string ivString = Convert.ToBase64String(iv);

                        return $"{encryptedPassword}-{ivString}";
                    }
                }
            }
        }

        /// <summary>
        /// Decrypts the password
        /// </summary>
        /// <param name="username"> Used to get the key for decryption </param>
        /// <returns> Plain password </returns>
        /// <exception cref="ArgumentException"> Thrown if plain password is not in a correct format </exception>
        public string DecryptPassword(string username)
        {
            byte[] key = GetKey(username);
            string plainPassword = "";

            // Split the encrypted password and IV
            string[] parts = Password.Split('-');
            if (parts.Length != 2)
            {
                throw new ArgumentException("The input string is not in the correct format.");
            }

            string encryptedPassword = parts[0];
            string ivString = parts[1];

            byte[] iv = Convert.FromBase64String(ivString);
            byte[] cipherText = Convert.FromBase64String(encryptedPassword);

            using (Aes aesAlg = Aes.Create())
            {
                aesAlg.Key = key;
                aesAlg.IV = iv;

                using (ICryptoTransform decryptor = aesAlg.CreateDecryptor(aesAlg.Key, aesAlg.IV))
                {
                    using (MemoryStream msDecrypt = new MemoryStream(cipherText))
                    {
                        using (CryptoStream csDecrypt = new CryptoStream(msDecrypt, decryptor, CryptoStreamMode.Read))
                        {
                            using (StreamReader srDecrypt = new StreamReader(csDecrypt))
                            {
                                plainPassword = srDecrypt.ReadToEnd();
                            }
                        }
                    }
                }
            }

            return plainPassword;
        }
    }
}